name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
        
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON ..
        cmake --build . --config Release
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Create DEB package
      run: |
        mkdir -p package/usr/local/bin
        mkdir -p package/DEBIAN
        cp build/house_theme_main package/usr/local/bin/
        
        cat > package/DEBIAN/control <<EOF
        Package: house-theme-bridge
        Version: 1.0
        Section: base
        Priority: optional
        Architecture: amd64
        Maintainer: vector2281337 <vvlukanin13@mail.ru>
        Description: House Theme Bridge Pattern Example
        EOF
        
        dpkg-deb --build package house-theme-bridge.deb
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: house-theme-bridge-package
        path: build/house-theme-bridge.deb
        
 
